// Code generated by protoc-bin.sh-gen-go. DO NOT EDIT.
// versions:
// 	protoc-bin.sh-gen-go v1.23.0
// 	protoc-bin.sh        v3.14.0
// source: proto/rudder-server/rudder-server.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StopSourceLiveEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopSourceLiveEventsRequest) Reset() {
	*x = StopSourceLiveEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSourceLiveEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSourceLiveEventsRequest) ProtoMessage() {}

func (x *StopSourceLiveEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSourceLiveEventsRequest.ProtoReflect.Descriptor instead.
func (*StopSourceLiveEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rudder_server_rudder_server_proto_rawDescGZIP(), []int{0}
}

type StopSourceLiveEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopSourceLiveEventsResponse) Reset() {
	*x = StopSourceLiveEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopSourceLiveEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSourceLiveEventsResponse) ProtoMessage() {}

func (x *StopSourceLiveEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSourceLiveEventsResponse.ProtoReflect.Descriptor instead.
func (*StopSourceLiveEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rudder_server_rudder_server_proto_rawDescGZIP(), []int{1}
}

type FetchSourceLiveEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceId string `protobuf:"bytes,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
}

func (x *FetchSourceLiveEventsRequest) Reset() {
	*x = FetchSourceLiveEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSourceLiveEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSourceLiveEventsRequest) ProtoMessage() {}

func (x *FetchSourceLiveEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSourceLiveEventsRequest.ProtoReflect.Descriptor instead.
func (*FetchSourceLiveEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rudder_server_rudder_server_proto_rawDescGZIP(), []int{2}
}

func (x *FetchSourceLiveEventsRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type FetchSourceLiveEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []string `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *FetchSourceLiveEventsResponse) Reset() {
	*x = FetchSourceLiveEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSourceLiveEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSourceLiveEventsResponse) ProtoMessage() {}

func (x *FetchSourceLiveEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rudder_server_rudder_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSourceLiveEventsResponse.ProtoReflect.Descriptor instead.
func (*FetchSourceLiveEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rudder_server_rudder_server_proto_rawDescGZIP(), []int{3}
}

func (x *FetchSourceLiveEventsResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_rudder_server_rudder_server_proto protoreflect.FileDescriptor

var file_proto_rudder_server_rudder_server_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x75, 0x64, 0x64, 0x65, 0x72, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x64, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1d, 0x0a, 0x1b, 0x73, 0x74, 0x6f, 0x70, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1e, 0x0a, 0x1c, 0x73, 0x74, 0x6f, 0x70, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x3a, 0x0a, 0x1c, 0x66, 0x65, 0x74, 0x63, 0x68, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1d, 0x66,
	0x65, 0x74, 0x63, 0x68, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x32, 0xd9, 0x01, 0x0a, 0x10, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c,
	0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x64, 0x0a, 0x15, 0x66, 0x65, 0x74,
	0x63, 0x68, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x65, 0x74, 0x63, 0x68,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x66, 0x65, 0x74, 0x63, 0x68, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x5f, 0x0a, 0x14, 0x73, 0x74, 0x6f, 0x70, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x76,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x73, 0x74, 0x6f, 0x70, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x74, 0x6f, 0x70, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x76, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x75, 0x64, 0x64, 0x65, 0x72, 0x6c, 0x61, 0x62, 0x73, 0x2f, 0x72, 0x75, 0x64, 0x64, 0x65, 0x72,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rudder_server_rudder_server_proto_rawDescOnce sync.Once
	file_proto_rudder_server_rudder_server_proto_rawDescData = file_proto_rudder_server_rudder_server_proto_rawDesc
)

func file_proto_rudder_server_rudder_server_proto_rawDescGZIP() []byte {
	file_proto_rudder_server_rudder_server_proto_rawDescOnce.Do(func() {
		file_proto_rudder_server_rudder_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rudder_server_rudder_server_proto_rawDescData)
	})
	return file_proto_rudder_server_rudder_server_proto_rawDescData
}

var file_proto_rudder_server_rudder_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rudder_server_rudder_server_proto_goTypes = []interface{}{
	(*StopSourceLiveEventsRequest)(nil),   // 0: proto.stopSourceLiveEventsRequest
	(*StopSourceLiveEventsResponse)(nil),  // 1: proto.stopSourceLiveEventsResponse
	(*FetchSourceLiveEventsRequest)(nil),  // 2: proto.fetchSourceLiveEventsRequest
	(*FetchSourceLiveEventsResponse)(nil), // 3: proto.fetchSourceLiveEventsResponse
}
var file_proto_rudder_server_rudder_server_proto_depIdxs = []int32{
	2, // 0: proto.SourceLiveEvents.fetchSourceLiveEvents:input_type -> proto.fetchSourceLiveEventsRequest
	0, // 1: proto.SourceLiveEvents.stopSourceLiveEvents:input_type -> proto.stopSourceLiveEventsRequest
	3, // 2: proto.SourceLiveEvents.fetchSourceLiveEvents:output_type -> proto.fetchSourceLiveEventsResponse
	1, // 3: proto.SourceLiveEvents.stopSourceLiveEvents:output_type -> proto.stopSourceLiveEventsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rudder_server_rudder_server_proto_init() }
func file_proto_rudder_server_rudder_server_proto_init() {
	if File_proto_rudder_server_rudder_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rudder_server_rudder_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSourceLiveEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rudder_server_rudder_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopSourceLiveEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rudder_server_rudder_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSourceLiveEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rudder_server_rudder_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSourceLiveEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rudder_server_rudder_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rudder_server_rudder_server_proto_goTypes,
		DependencyIndexes: file_proto_rudder_server_rudder_server_proto_depIdxs,
		MessageInfos:      file_proto_rudder_server_rudder_server_proto_msgTypes,
	}.Build()
	File_proto_rudder_server_rudder_server_proto = out.File
	file_proto_rudder_server_rudder_server_proto_rawDesc = nil
	file_proto_rudder_server_rudder_server_proto_goTypes = nil
	file_proto_rudder_server_rudder_server_proto_depIdxs = nil
}
